### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by za-wa-n-go** [Limitex/ComfyUI-Diffusers#1]
こちら現状は複数枚を高速に生成保存するためのノードとしてとりあえず動かしてみた、という認識であっていますでしょうか。

StableDiffusionを使いたい人間はwebカメラやデスクトップの特定領域をリアルタイムに取り込んでi2iを実行する形を期待していると思うので、それが容易に使用出来るようになるノードになると嬉しいです。

**Comment by Limitex** [comment]
はい、今のところはそのような認識であっていますが、今後も機能を追加していく予定です。
また、リポジトリの名前の通り、DiffusersモジュールをComfyUIで利用できるようにしていくものになっているので、StreamDiffusionはサブの位置付けになるかなと思います。
ですが、
>StableDiffusionを使いたい人間はwebカメラやデスクトップの特定領域をリアルタイムに取り込んでi2iを実行する形を期待していると思うので、それが容易に使用出来るようになるノードになると嬉しいです。
この機能も面白そうなので追加できたらと思います。

**Comment by Limitex** [comment]
This issue has been merged into https://github.com/Limitex/ComfyUI-Diffusers/issues/7
