### ISSUE TITLE
(install issuse) Will it reinstall torch version in comfyui ? Restart ComfyUI shows Torch CUDA imcompatible, with ComfyUI python_embeded version.

### ISSUE THREAD

**Issue by Erwin11** [Limitex/ComfyUI-Diffusers#13]
### **install methods:**
1. git clone https://github.com/Limitex/ComfyUI-Diffusers.git
2. cd ComfyUI-Diffusers
3. pip install -r requirements.txt
4. git clone https://github.com/cumulo-autumn/StreamDiffusion.git
5. python -m streamdiffusion.tools.install-tensorrt

### **what I did:**
in this folder: ComfyUI\custom_nodes\   
1. shows some issuses:
![diffuser requirement -1](https://github.com/Limitex/ComfyUI-Diffusers/assets/6300501/d6f54e0c-56d9-4212-a487-522f019b85f6)
![diffuser requirement -2](https://github.com/Limitex/ComfyUI-Diffusers/assets/6300501/faefb703-7e1e-49b4-a99d-f020546b128a)

2 are the same.
3. in ComfyUI-Diffusers folder: ..\..\..\python_embeded\python.exe pip install -r requirements.txt
4. in ComfyUI-Diffusers folder: git clone https://github.com/cumulo-autumn/StreamDiffusion.git
5. in ComfyUI-Diffusers folder: ..\..\..\python_embeded\python.exe -m streamdiffusion.tools.install-tensorrt
	Error:
	WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.2+cpu)
    Python  3.11.7 (you have 3.11.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

and I restarted comfyUI, 
   Error: 
   shows Torch CUDA imcompatible

So， I use  ComfyUI_windows_portable\update\update_comfyui_and_python_dependencies.bat
 to reinstall  torch torchvision torchaudio  --extra-index-url https://download.pytorch.org/whl/cu121 
![reinstall torch](https://github.com/Limitex/ComfyUI-Diffusers/assets/6300501/6b40ce54-14d5-46b1-b966-7aea22274c74)

 restart comfyUI, ok, it works.

redo No.5 method
no Xfromers Error again.
![streamdiffusion tools install-tensorrt  -1](https://github.com/Limitex/ComfyUI-Diffusers/assets/6300501/7b45f3f1-af9a-4151-b754-d64986dde266)
![streamdiffusion tools install-tensorrt  -2](https://github.com/Limitex/ComfyUI-Diffusers/assets/6300501/abba1bc5-ec84-4275-9589-7d7a6fceaece)

_Workflow can be imported, without Error._

So, here is my process, I hope it could help for others. 

### **My thoughts**
I think some python requirements is imcompatible, maybe xfrommers version? I'm not familiar with python, can't debug it.
https://blog.comfyui.ca/comfyui/update/2023/10/08/Weekly-update.html
the news shows comfyui remove xformers. it might be help.

**Comment by Limitex** [comment]
Thank you for the report. xformers was used in the Stream Diffusion official repository, so if it is discontinued there, I think it will be removed here as well.

**Comment by curlysasha** [comment]
> Thank you for the report. xformers was used in the Stream Diffusion official repository, so if it is discontinued there, I think it will be removed here as well.

you plan to fix this issue?

**Comment by Shangnei** [comment]
very grateful
