### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by killporter** [Limitex/ComfyUI-Diffusers#3]
works terribly as speed compared to stable fast, doesn't offer any acceleration and locks the number of warmup steps 
apprently has problems with turbo as well
no lcm, no choice or i don't know if even uses tensorrt or anything

**Comment by Limitex** [comment]
Thank you for publishing the issues. We are currently working on a fix for this issue. It's still a work in progress, but I'm pushing a fix commit to the "new" branch

**Comment by Limitex** [comment]
https://github.com/Limitex/ComfyUI-Diffusers/pull/4 Fixed with this pull request
